stages:
  - build

.build:
  stage: build
  image: docker:18.09
  services:
    - name: docker:18.09-dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-image:
  extends: .build
  script:
    - docker --debug build . -f ./Dockerfile -t ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/goinception:${CI_COMMIT_REF_SLUG}
    - docker push ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/goinception:${CI_COMMIT_REF_SLUG}
    - docker rmi -f ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/goinception:${CI_COMMIT_REF_SLUG}
