# TiDB Configuration.

# TiDB server host.
host = "0.0.0.0"

# tidb server advertise IP.
advertise_address = ""

# TiDB server port.
port = 4000

# path = ""

[inc]
enable_nullable = true
enable_drop_table = true
enable_column_charset = false

max_primary_key_parts = 3
max_keys = 3
max_key_parts = 3
max_update_rows = 5000

check_table_comment = false
check_column_comment = false
check_index_prefix = false


backup_host = "127.0.0.1"
backup_port = 20001
backup_user = "inception"
backup_password = "inception"


# 安全更新是否开启.
# -1 表示不做操作,基于远端数据库 [默认值]
# 0  表示关闭安全更新
# 1  表示开启安全更新
sql_safe_updates = 0

[osc]
osc_on = true
osc_min_table_size = 0
osc_print_none = true


[log]
# Log level: debug, info, warn, error, fatal.
level = "info"
# Log format, one of json, text, console.
format = "console"


[security]
skip-grant-table = true
