# TiDB Configuration.

# TiDB server host.
host = "0.0.0.0"

# tidb server advertise IP.
advertise_address = ""

# TiDB server port.
port = 4000

# path = ""

[inc]
enable_nullable = true
enable_drop_table = true
enable_column_charset = false

max_primary_key_parts = 3
max_keys = 3
max_key_parts = 3
max_update_rows = 5000

check_table_comment = false
check_column_comment = false
check_index_prefix = false


backup_host = "127.0.0.1"
# backup_port = 20001
# backup_user = "inception"
# backup_password = "inception"
backup_port = 3306
backup_user = "test"
backup_password = "test"


# 安全更新是否开启.
# -1 表示不做操作,基于远端数据库 [默认值]
# 0  表示关闭安全更新
# 1  表示开启安全更新
sql_safe_updates = 0

# lang = "en-US"
# lang = "zh-CN"

[osc]
osc_on = false
osc_min_table_size = 16
osc_print_none = false
osc_bin_dir = "/usr/local/bin"

[ghost]

ghost_on = false
ghost_allow_on_master = true
ghost_assume_rbr = true
ghost_chunk_size = 1000
ghost_concurrent_rowcount = true
ghost_cut_over = "atomic"
ghost_cut_over_lock_timeout_seconds = 3
ghost_default_retries = 60
ghost_heartbeat_interval_millis = 500
ghost_max_lag_millis = 1500
ghost_approve_renamed_columns = true
ghost_exponential_backoff_max_interval = 64
ghost_dml_batch_size = 10

[log]
# Log level: debug, info, warn, error, fatal.
level = "info"
# Log format, one of json, text, console.
format = "console"

# File logging.
[log.file]
# Log file name.
filename = "go.log"