# TiDB Configuration.

# TiDB server host.
host = "0.0.0.0"

# tidb server advertise IP.
advertise_address = ""

# TiDB server port.
port = 4000

[inc]
enable_nullable = true
enable_drop_table = true
max_primary_key_parts = 3
max_keys = 3
check_table_comment = false
check_column_comment = false

backup_host = "127.0.0.1"
backup_port = 20001
backup_user = "inception"
backup_password = "inception"

[log]
# Log level: debug, info, warn, error, fatal.
level = "info"
# Log format, one of json, text, console.
format = "console"
