# TiDB Configuration.

# TiDB server host.
host = "0.0.0.0"

# tidb server advertise IP.
advertise-address = ""

# TiDB server port.
port = 4000

[inc]
enable-nullable = true
enable-drop-table = false
max-primary-key-parts = 3
max-keys = 3
